swagger: "2.0"

info:
  title: "Elastic Search CRUD Example"
  version: "1.0"
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html

schemes:
 - https
 - http
# tags are used for organizing operations
tags:
- name: public
  description: Operations available to regular developers
- name: admins
  description: Secured Admin-only calls

paths:
  
  /heartbeat/:
    get:
      produces:
      - application/json
      operationId: api.elastic-crud.heartbeat
      responses:
        200:
          description: Success, your server is live