swagger: "2.0"

info:
  title: "Elastic Search CRUD Example"
  version: "1.0"
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html

schemes:
 - https
 - http
# tags are used for organizing operations
tags:
- name: CRUD
  description: Operations related to creating, reading, updating or deleting documents
- name: Query
  description: Operations which take in queries to perform a piece of work. For example searching documents

paths:
  
  /heartbeat/:
    get:
      summary: Returns 200, ensures the API is still alive
      produces:
      - application/json
      operationId: api.elastic-crud.heartbeat
      responses:
        200:
          description: Success, your server is live
  /insertDocument/:
    post:
      summary: Attempts to create a new document using the Index API 
      tags:
      - CRUD
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
        - in: query
          name: index
          type: string
        - in: query
          name: type
          type: string 
        - in: query
          name: id
          type: string 
          required: false 
        - in: body
          name: body
          description: The document details to be indexed
          schema:
            type: object
      operationId: api.elastic-crud.insertDocument
      responses:
        200:
          description: Success, your server is live
  /searchDocument/:
    post:
      summary: Searches the instance for documents which match the search query
      tags:
      - Query
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
        - in: query
          name: index
          type: string
          required: false 
        - in: query
          name: type
          type: string 
          required: false 
        - in: query
          name: id
          type: string 
          required: false 
        - in: body
          name: body
          description: The search query to be run
          schema:
            type: object
      operationId: api.elastic-query.searchDocument
      responses:
        200:
          description: Success, your server is live
  /deleteDocumentByQuery/{index}/{type}:
    post:
      summary: Searches the instance for documents which match the search query; Results are then deleted
      tags:
      - Query
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
        - in: path
          name: index
          type: string
          required: true 
        - in: path
          name: type
          type: string 
          required: true 
        - in: body
          name: query
          description: The delete query to be run
          schema:
            type: object
      operationId: api.elastic-query.deleteByQuery
      responses:
        201:
          description: Success, document deleted
  

  /document/{index}/{type}/{id}:
    get:
      summary: Attempts to GET a document by its index,type and ID
      tags:
      - CRUD
      produces:
      - application/json
      parameters:
        - in: path
          name: index
          type: string
          required: true 
        - in: path
          name: type
          type: string 
          required: true 
        - in: path
          name: id
          type: string 
          required: true 
      operationId: api.elastic-crud.getDocumentById
      responses:
        200:
          description: Success, your server is live
    delete:
      summary: Attempts to DELETE a document by its index,type and ID
      tags:
      - CRUD
      produces:
      - application/json
      parameters:
        - in: path
          name: index
          type: string
          required: true 
        - in: path
          name: type
          type: string 
          required: true 
        - in: path
          name: id
          type: string 
          required: true 
      operationId: api.elastic-crud.deleteDocumentById
      responses:
        200:
          description: Success, document deleted
    put:
      summary: Attempts to GET a document by its index,type and ID and then updates it with information provided in the body
      tags:
      - CRUD
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
        - in: path
          name: index
          type: string
          required: true 
        - in: path
          name: type
          type: string 
          required: true 
        - in: path
          name: id
          type: string 
          required: true 
        - in: body
          name: body
          description: The search query to be run
          schema:
            type: object
      operationId: api.elastic-crud.updateDocumentById
      responses:
        201:
          description: Success, document deleted
  