swagger: "2.0"

info:
  title: "Elastic Search CRUD Example"
  version: "1.0"
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html

schemes:
 - https
 - http
# tags are used for organizing operations
tags:
- name: public
  description: Operations available to regular developers
- name: admins
  description: Secured Admin-only calls

paths:
  
  /heartbeat/:
    get:
      produces:
      - application/json
      operationId: api.elastic-crud.heartbeat
      responses:
        200:
          description: Success, your server is live
  /insertDocument/:
    post:
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
        - in: query
          name: index
          type: string
        - in: query
          name: type
          type: string 
        - in: query
          name: id
          type: string 
          required: false 
        - in: body
          name: body
          description: The document details to be indexed
          schema:
            type: object
      operationId: api.elastic-crud.insertDocument
      responses:
        200:
          description: Success, your server is live
  /searchDocument/:
    post:
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
        - in: query
          name: index
          type: string
        - in: query
          name: type
          type: string 
        - in: query
          name: id
          type: string 
          required: false 
        - in: body
          name: body
          description: The search query to be run
          schema:
            type: object
      operationId: api.elastic-crud.searchDocument
      responses:
        200:
          description: Success, your server is live